behaviors:
  BlueAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1000
      buffer_size: 10240
      learning_rate: 1.0e-5
      beta: 1.0e-2
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      shared_critic: true
    network_settings:
      vis_encode_type: simple
      normalize: false
      hidden_units: 512
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 500000
    time_horizon: 64
    summary_freq: 5000

  RedAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1000
      buffer_size: 10240
      learning_rate: 1.0e-5
      beta: 1.0e-2
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      shared_critic: true
    network_settings:
      vis_encode_type: simple
      normalize: false
      hidden_units: 512
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 500000
    time_horizon: 64
    summary_freq: 5000

